# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: .
      Contents: |
        myapp.yaml
        myservice.yaml
      TargetFolder: ${Build.ArtifactStagingDirectory}
  - task: KubernetesManifest@0
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: 'cluster-connection'
      namespace: 'default'
      manifests: |
        ${Build.ArtifactStagingDirectory}/myapp.yaml
        ${Build.ArtifactStagingDirectory}/myservice.yaml
      containers: |
        az400appregistry.azurecr.io/az400nginx:latest
  