# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: .
      Contents: |
        myapp.yaml
        myservice.yaml
      TargetFolder: ${Build.ArtifactStagingDirectory}
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'AshAzure (a086965e-3fe0-4601-9015-ad423c0fc6ef)'
      appType: 'webAppContainer'
      WebAppName: 'az400webappcontainer'
      DockerNamespace: 'az400appregistry.azurecr.io'
      DockerRepository: 'az400nginx'
      DockerImageTag: 'latest'
  